name: GitHub Pages

on:
  release:
    types:
      - created
      - edited

jobs:
  job:
    name: GitHub Pages
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_CREATE: false
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Build docs
        run: docs/build
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build
          publish_branch: gh-pages
          force_orphan: true
